version: '3.3'
services:
  consultant_portal:
    build: .
    ports: 
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:\app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ftp-server:
    container_name: my-ftp-server
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - '/ftp_data:/home/user'