version: '3.3'
services:
  consultant_portal:
    build: .
    ports: 
      - '3000:3000'
    volumes:
      - .:\app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"

  